from enum import Enum

class TokenType(Enum):
    NUM_LIT	    = 'NUM_LIT'
    STRING_LIT    = 'STRING_LIT'
    DATE_LIT     = 'DATE_LIT'
    BOOL_LIT     = 'BOOL_LIT'
    COLON     = ':'
    SEMICOLON = ';'
    PLUS      = '+'
    MINUS     = '-'
    MUL       = '*'
    DIV       = '/'
    POWER     = 'POWER'
    LPAREN    = '('
    RPAREN    = ')'
    EQUAL     = '='
    EQUALOP   = '=='
    GREATEROP = '>'
    LESSOP    = '<'
    GEQ       = '>='
    LEQ       = '<='
    INEQ      = '!='
    SLASH     = '\\'
    LSQBRACKER= '['
    RSQBRACKER= ']'
    COMMA     = ','
    NEWLINE	= '\n'
    KEYWORD	= 'KEYWORD'
    IDENTIFIER= 'IDENTIFIER'
    EOF       = 'EOF'
    FUNC = 'FUNC'
    AND  = 'AND'
    OR = 'OR'
    MAIN  = 'MAIN'
    IF   = 'IF'
    ARRAY  = 'ARRAY'
    ELSE = 'ELSE'
    UNTIL  = 'UNTIL'
    NUM = 'NUM'
    STRING= 'STRING'
    DATE = 'DATE'
    BOOL = 'BOOL'
    RETURN = 'RETURN'
    TRUE = 'TRUE'
    FALSE  = 'FALSE'
    PRINT = 'PRINT'
    NOT = 'NOT'

